In [14]:
import tensorflow as tf
import numpy as np

In [45]:
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]


X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(20):
        cost_val, W_val, _ = sess.run([cost,W, optimizer],
                                     feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print("prediction:",sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))


0 3.17198 [[ 0.75524276 -0.7102165  -2.075336  ]
 [-0.04150367 -1.5786031   1.3579409 ]
 [ 0.11374709  1.8337309  -0.20754643]]
1 2.9869065 [[ 0.7571865  -0.70913666 -2.0783596 ]
 [-0.02669755 -1.5681887   1.3327203 ]
 [ 0.12895598  1.8409071  -0.2299315 ]]
2 2.8121 [[ 0.7590543  -0.7081869  -2.0811772 ]
 [-0.01214197 -1.5583535   1.3083296 ]
 [ 0.14396392  1.8474932  -0.25152555]]
3 2.6489525 [[ 0.7608358  -0.70738095 -2.0837648 ]
 [ 0.00210994 -1.5492005   1.2849246 ]
 [ 0.1587216   1.8533939  -0.272184  ]]
4 2.498989 [[ 0.7625191  -0.70673305 -2.086096  ]
 [ 0.01599404 -1.5408386   1.2626785 ]
 [ 0.17316845  1.8585063  -0.29174325]]
5 2.3636122 [[ 0.7640914  -0.7062549  -2.0881464 ]
 [ 0.02943623 -1.533364    1.2417617 ]
 [ 0.18723364  1.8627383  -0.31004038]]
6 2.2437932 [[ 0.7655393  -0.705952   -2.0898972 ]
 [ 0.04235531 -1.5268384   1.222317  ]
 [ 0.20083892  1.866031   -0.32693842]]
7 2.1398242 [[ 0.7668499  -0.7058208  -2.0913389 ]
 [ 0.05466752 -1.5212702   1.2044365 ]
 [ 0.2

In [13]:
#learning rate (overshooting)
#training data set으로 학습시킨다. 
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

#test data set으로 학습 이후, 모델을 test하는데 사용된다.  
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

X = tf.placeholder("float",[None, 3])
Y = tf.placeholder("float",[None, 3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis),axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-10).minimize(cost)

prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(20):
        cost_val, W_val, _ = sess.run([cost,W, optimizer],
                                     feed_dict={X:x_data, Y:y_data})
        print(step, cost_val, W_val)
    print("prediction:",sess.run(prediction, feed_dict={X:x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))


0 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
1 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
2 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
3 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
4 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
5 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
6 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]
 [ 0.8957778   0.3747913   0.4818684 ]]
7 2.0651903 [[ 1.4471973  -0.2853669   0.16718894]
 [-0.44996938 -0.19693238 -0.73534155]


In [46]:
#Non normalized inputs

xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]),name = "weight")
b = tf.Variable(tf.random_normal([1]),name = "bias")

hypothesis = tf.matmul(X,W) +b
cost = tf.reduce_mean(tf.square(hypothesis-Y))
train = tf.train.GradientDescentOptimizer(learning_rate = 1e-10).minimize(cost)

sess =tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X:x_data,Y:y_data})
    if step%200 == 0 :
        print(step, "Cost: ", cost_val, "\nPrediction:\n",hy_val)

0 Cost:  5883343000000.0 
Prediction:
 [[-1711253.5]
 [-3442230.5]
 [-2708428.8]
 [-1899365. ]
 [-2238046.8]
 [-2256858.2]
 [-2068684.4]
 [-2633132.5]]
200 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
400 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
600 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
800 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1000 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1200 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1400 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1600 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1800 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
2000 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [na

In [67]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility



xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)


# very important. It does not work without it.


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    return numerator / denominator

xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function

l2reg = 0.001 * tf.reduce_sum(tf.square(W))
cost = tf.reduce_mean(tf.square(hypothesis - Y))+l2reg

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        if step % 100 == 0 :
            print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

'''
0 Cost: 0.15230925 
Prediction:
 [[ 1.6346191 ]
 [ 0.06613699]
 [ 0.3500818 ]
 [ 0.6707252 ]
 [ 0.61130744]
 [ 0.61464405]
 [ 0.23171967]
 [-0.1372836 ]]
1 Cost: 0.15230872 
Prediction:
 [[ 1.634618  ]
 [ 0.06613836]
 [ 0.35008252]
 [ 0.670725  ]
 [ 0.6113076 ]
 [ 0.6146443 ]
 [ 0.23172   ]
 [-0.13728246]]
...
99 Cost: 0.1522546 
Prediction:
 [[ 1.6345041 ]
 [ 0.06627947]
 [ 0.35014683]
 [ 0.670706  ]
 [ 0.6113161 ]
 [ 0.61466044]
 [ 0.23175153]
 [-0.13716647]]
100 Cost: 0.15225402 
Prediction:
 [[ 1.6345029 ]
 [ 0.06628093]
 [ 0.35014752]
 [ 0.67070574]
 [ 0.61131614]
 [ 0.6146606 ]
 [ 0.23175186]
 [-0.13716528]]
'''


[[1.         1.         0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881783 0.83755792]
 [0.54412549 0.50274824 0.57608696 0.60646801 0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.4258239  0.30434783 0.58504805 0.42624401]
 [0.49556179 0.4258239  0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  1.0267836 
Prediction:
 [[1.7656009 ]
 [0.98848885]
 [1.3379936 ]
 [1.6433437 ]
 [1.5928441 ]
 [1.516614  ]
 [1.6326141 ]
 [1.0793518 ]]
100 Cost:  1.0213168 
Prediction:
 [[1.7615192 ]
 [0.98449236]
 [1.3345735 ]
 [1.6405766 ]
 [1.5896639 ]
 [1.5135278 ]
 [1.6303586 ]
 [1.0771325 ]]
200 Cost:  1.0158837 
Prediction:
 [[1.7574475]
 [0.9805085]
 [1.3311629]
 [1.6378156]
 [1.5864917]
 [1.5104493]
 [1.6281078]
 [1.074918 ]]
300 Cost:  1.0104963 
Prediction:
 [[1.7533929]
 [0.9765412]
 [1.3277676]
 [1.6350678]
 [1.5833341]
 

'\n0 Cost: 0.15230925 \nPrediction:\n [[ 1.6346191 ]\n [ 0.06613699]\n [ 0.3500818 ]\n [ 0.6707252 ]\n [ 0.61130744]\n [ 0.61464405]\n [ 0.23171967]\n [-0.1372836 ]]\n1 Cost: 0.15230872 \nPrediction:\n [[ 1.634618  ]\n [ 0.06613836]\n [ 0.35008252]\n [ 0.670725  ]\n [ 0.6113076 ]\n [ 0.6146443 ]\n [ 0.23172   ]\n [-0.13728246]]\n...\n99 Cost: 0.1522546 \nPrediction:\n [[ 1.6345041 ]\n [ 0.06627947]\n [ 0.35014683]\n [ 0.670706  ]\n [ 0.6113161 ]\n [ 0.61466044]\n [ 0.23175153]\n [-0.13716647]]\n100 Cost: 0.15225402 \nPrediction:\n [[ 1.6345029 ]\n [ 0.06628093]\n [ 0.35014752]\n [ 0.67070574]\n [ 0.61131614]\n [ 0.6146606 ]\n [ 0.23175186]\n [-0.13716528]]\n'